/** This file is auto-generated by Plasmic; please do not edit! */

import { useEffect, useState } from "react";
import * as React from "react";
import PlasmicLoader from "@plasmicapp/loader";

const slides = ["first", "second", "third"];
const timeBetweenSlides = 5000; // 5 seconds

export default function PageComponent() {
  const [currentSlide, setCurrentSlide] = useState(0);
  useEffect(() => {
    const interval = setInterval(
      () => setCurrentSlide((currentSlide + 1) % slides.length),
      timeBetweenSlides
    );

    return () => clearInterval(interval);
  });

  return (
    <PlasmicLoader
      projectId="uxghh7Jr8fCv7BzYM4RdvS"
      component="Home"
      componentProps={{
        productCarousel: { props: { slider: slides[currentSlide] } },
      }}
    />
  );
}
